version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
      - ws
    volumes:
      - ./frontend:/app
    dns:
      - 8.8.8.8
      - 1.1.1.1

  ws:
    build:
      context: .
      dockerfile: Dockerfile.ris_ws
    ports:
      - "8765:8765"
    volumes:
      - ./backend:/app
    depends_on:
      - backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8765/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
